name: sonora
description: "A local music player for Android with Material 3 Expressive design."
publish_to: 'none'
version: 1.4.0+1

environment:
  sdk: ^3.12.2

dependencies:
  audio_service: ^0.18.19
  audio_service_win: ^0.0.3
  audio_session: ^0.2.4
  audio_tags_lofty: ^0.0.6
  file_picker: ^12.0.0-beta.7
  flutter:
    sdk: flutter
  go_router: ^17.3.0
  google_fonts: ^8.2.0
  just_audio: ^0.10.6
  just_audio_windows: ^0.2.3
  package_info_plus: ^10.2.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

# dart run flutter_launcher_icons
flutter_launcher_icons:
  android: 'ic_launcher'
  adaptive_icon_background: "assets/icon/ic_launcher_background.png"
  adaptive_icon_foreground: "assets/icon/ic_launcher_foreground.png"
  adaptive_icon_monochrome: "assets/icon/ic_launcher_monochrome.png"
  ios: false
  image_path: "assets/icon/ic_launcher.png"
  min_sdk_android: 24
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
